
// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCEk-jRtCnxcFdly_iMS545UOATTXvq8EM',
    appId: '1:780496859647:web:ceb0f5603a4666089237ca',
    messagingSenderId: '780496859647',
    projectId: 'vibetours-e614d',
    authDomain: 'vibetours-e614d.firebaseapp.com',
    storageBucket: 'vibetours-e614d.firebasestorage.app',
    measurementId: 'G-7KGDEMVB01',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyChVRqJFFXdmndJE4q1yZ_YIGrxxk5MGDk',
    appId: '1:780496859647:android:e3c14363c55b7a8a9237ca',
    messagingSenderId: '780496859647',
    projectId: 'vibetours-e614d',
    storageBucket: 'vibetours-e614d.firebasestorage.app',
  );
  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDl3uHRWwJosS50pSZhIT8t2sfTYXDF6oU',
    appId: '1:780496859647:ios:1f6e39b2bfda5b429237ca',
    messagingSenderId: '780496859647',
    projectId: 'vibetours-e614d',
    storageBucket: 'vibetours-e614d.firebasestorage.app',
    iosBundleId: 'com.example.vibetoursapp',
  );
  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDl3uHRWwJosS50pSZhIT8t2sfTYXDF6oU',
    appId: '1:780496859647:ios:1f6e39b2bfda5b429237ca',
    messagingSenderId: '780496859647',
    projectId: 'vibetours-e614d',
    storageBucket: 'vibetours-e614d.firebasestorage.app',
    iosBundleId: 'com.example.vibetoursapp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCEk-jRtCnxcFdly_iMS545UOATTXvq8EM',
    appId: '1:780496859647:web:4ba6eff6217de2e99237ca',
    messagingSenderId: '780496859647',
    projectId: 'vibetours-e614d',
    authDomain: 'vibetours-e614d.firebaseapp.com',
    storageBucket: 'vibetours-e614d.firebasestorage.app',
    measurementId: 'G-KKD80T51FT',
  );
}
